name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  deploy-web:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Copy Docker image to root
      run: cp ./docker/web/Dockerfile .

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: pushh02/frontend:latest

    - name: Verify Pushed Image
      run: docker pull pushh02/coding-genius:latest